name: Configuration Variables

on:
  workflow_dispatch

jobs:
  bulid:
      runs-on: ubutnu-lastest
      steps:
      - name: Ouput vars
        run: |
        echo "REPO_VAR1": ${{vars.REPO_VAR1}}

  using-environmets:
    runs-on: ubuntu-lastest
    environment:
      name: DEV

    steps: 
    - name:
      run: |
      echo "ENV_VAR1: ${{vars.ENV_VAR1}}"