name: Configuration Variables

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Output vars
      run: |
        echo "REPO_VAR1: ${{ secrets.REPO_VAR1 }}"
        echo "ENV_VAR1: ${{ secrets.ENV_VAR1 }}"

  using-environments:
    runs-on: ubuntu-latest
    env:
      REPO_VAR1: ${{ secrets.REPO_VAR1 }}
      ENV_VAR1: ${{ secrets.ENV_VAR1 }}

    steps:
    - name: Show Variables
      run: |
        echo "REPO_VAR1: $REPO_VAR1"
        echo "ENV_VAR1: $ENV_VAR1"