name: Configuration Variables

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Output vars
      run: |
        echo "REPO_VAR1: ${{ vars.REPO_VAR1 }}"

  using-environments:
    runs-on: ubuntu-latest
    environment:
      name: DEV

    steps:
    - name: Output some more vars
      run: |
        echo "ENV_VAR1: ${{ vars.ENV_VAR1 }}"